In [269]:
import numpy as np
a = np.array([[1, 2, 3], [5, 8, 7]])
print("Array created using passed list:\n", a)


Array created using passed list:
 [[1 2 3]
 [5 8 7]]


In [270]:
#Creating a 3x4 array with all zeros
b = np.zeros((3, 4))
print("An array initialized with zeros:\n", b)

An array initialized with zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [271]:
#Create a constant value array of complex type
c = np.full((3, 3), 8)
print("An array initialized with constant values:\n", c)

An array initialized with constant values:
 [[8 8 8]
 [8 8 8]
 [8 8 8]]


In [272]:
#Create an array with random values
d = np.random.random((2, 2))
print("An array initialized with random values:\n", d)

An array initialized with random values:
 [[0.7393227  0.78752969]
 [0.59016875 0.64101429]]


In [273]:
#Create a sequence of numbers from 0 to 30 with a step of 5
e = np.arange(0, 30, 5)
print("Array of evenly spaced values (step value):\n", e)

Array of evenly spaced values (step value):
 [ 0  5 10 15 20 25]


In [274]:
#Reshaping 3x4 array to 2x2x6 array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
newarr = arr.reshape(4, 3)
print("Original array:\n", arr)
print("Reshaped array:\n", newarr)

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [275]:
#Flatten array 
flarr = arr.flatten()
print("Original array:\n", arr)
print("Flattened array:\n", flarr)

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [276]:
#Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)

No. of dimensions:  2


In [277]:
#Printing shape of array
print("Shape of array: ", arr.shape)

Shape of array:  (3, 4)


In [278]:
#Printing size (total number of elements) of array
print("Size of array: ", arr.size)

Size of array:  12


In [279]:
#Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array stores elements of type:  int64


In [280]:
#Converting datatypes from integer to float
newtype = arr.astype('f')
print("Converted array elements:\n", newtype)
print("Converted array type:\n", newtype.dtype)

Converted array elements:
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
Converted array type:
 float32


In [281]:
import numpy as np
p = np.array([[1, 2, 3], [5, 8, 7]])
print(p[1:0:-1])

[[5 8 7]]


In [282]:
import numpy as np
p = np.array([[1, 2, 3], [5, 8, 7]])
print(p[2:0:-2])

[[5 8 7]]


In [283]:
p = np.array([[1, 2, 3], [5, 8, 7], [9, 10, 11], [13, 14, 15]])
print(p[2:, 2:])

[[11]
 [15]]


In [284]:
p = np.array([[1, 2, 3], [5, 8, 7], [9, 10, 11], [13, 14, 15], [17, 18, 19]])
print(p[:3:, :3:])

[[ 1  2  3]
 [ 5  8  7]
 [ 9 10 11]]


In [285]:
p = np.array([[1, 2, 3], [5, 8, 7], [9, 10, 11], [13, 14, 15]])
print(p[:1])

[[1 2 3]]


In [286]:
p = np.array([[1, 2, 3], [5, 8, 7], [9, 10, 11], [13, 14, 15]])
c = p.astype('f')
print(c)

[[ 1.  2.  3.]
 [ 5.  8.  7.]
 [ 9. 10. 11.]
 [13. 14. 15.]]


In [287]:
p = np.array([[1, 2, 3], [5, 8, 7], [9, 10, 11], [13, 14, 15]])
c = p.astype('i')
print(c)

[[ 1  2  3]
 [ 5  8  7]
 [ 9 10 11]
 [13 14 15]]
