#### Aim: 
To retrieve array indices, perform basic index based operations, apply sorting techniques, and filter array values using Numpy.

#### Description:
- Do the index retrieval
- Do the basic operation with respect to index
- Do the sorting operation of an array
- Do the filtering of the array values

#### Programs:

In [ ]:
import numpy as np

#indexes where the value is 4:
arr = np.array ([1, 2, 3, 4, 5, 4, 4])
print("Original array:\n", arr)
x = np.where(arr==4)
print("\nIndexes where the values are 4:", x)

Original array:
 [1 2 3 4 5 4 4]

Indexes where the values are 4: (array([3, 5, 6], dtype=int64),)


In [ ]:
#indexes where the values are even:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x=np.where(arr%2==0)
print("\nOriginal array:\n", arr)
print("\nIndexes where the values are even:", x)


Original array:
 [1 2 3 4 5 6 7 8]

Indexes where the values are even: (array([1, 3, 5, 7], dtype=int64),)


In [ ]:
#indexes where the value 3 should be inserted, starting from the right
x=np.searchsorted(arr, 3, side='left')
print("Indexes where the value 3 should be inserted, starting from the right: 2")

Indexes where the value 3 should be inserted, starting from the right: 2


In [ ]:
#Sorting the array
arr=np.array([3, 2, 0, 1])
print("Original array:\n", arr)
print("\nSorted array:\n", np.sort(arr))
arr=np.array([[3, 2, 4], [5, 0, 1]])
print("\nOriginal array:\n", arr)
print("\nSorted array:\n", np.sort(arr))

Original array:
 [3 2 0 1]

Sorted array:
 [0 1 2 3]

Original array:
 [[3 2 4]
 [5 0 1]]

Sorted array:
 [[2 3 4]
 [0 1 5]]


In [ ]:
#Filter
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print("Original array:", arr)
print("\nFilter index:", x)
print("\nFilter array:", newarr)

Original array: [41 42 43 44]

Filter index: [True, False, True, False]

Filter array: [41 43]


In [ ]:
arr = np.array([41, 42, 43, 44])
filter_arr = [True, False, True, False]
newarr = arr[filter_arr]
print("Original array:", arr)
print("\nFilter array:condition->42:", filter_arr)
print("\nFilter array:", newarr)

Original array: [41 42 43 44]

Filter array:condition->42: [True, False, True, False]

Filter array: [41 43]
