#### Aim: 
To perform array slicing and indexing operation towards demonstrating various array joining techniques and apply array splittings method using Numpy.

#### Description:
- Perform different forms of slicing.
- Assign index
- Do the different join function, horizontal join, vertical join and depth join

#### Programs:

In [ ]:
import numpy as np

arr=np.array([[-1, 2, 0, 4], [4, -05.5, 6, 0], [2.9, 0, 7, 6], [3, -7, 4, 2.0]])
print(arr)
print(arr.shape)
print(arr.ndim)

[[-1.   2.   0.   4. ]
 [ 4.  -5.5  6.   0. ]
 [ 2.9  0.   7.   6. ]
 [ 3.  -7.   4.   2. ]]
(4, 4)
2


In [ ]:
#Returns every other rows:
print("Every other rows:\n", arr[0:3:2])

Every other rows:
 [[-1.   2.   0.   4. ]
 [ 2.9  0.   7.   6. ]]


In [ ]:
#Return every other element
arr=np.array([1, 2, 3, 4, 5, 6, 7])
print("Original array:", arr)
print("Return every other elements in the array: ", arr[::2])

Original array: [1 2 3 4 5 6 7]
Return every other elements in the array:  [1 3 5 7]


In [ ]:
#Slicing array
temp=arr[:2, :3]
print("Array with first 2 rows and three columns is:\n", temp)

Array with first 2 rows and three columns is:
 [[-1.   2.   0. ]
 [ 4.  -5.5  6. ]]


In [ ]:
print(arr[0:3:2])

[[-1.   2.   0.   4. ]
 [ 2.9  0.   7.   6. ]]


In [ ]:
print(arr[0:3, 0:3])

[[-1.   2.   0. ]
 [ 4.  -5.5  6. ]
 [ 2.9  0.   7. ]]


In [ ]:
print(arr[::2, ::4])

[[-1. ]
 [ 2.9]]


In [ ]:
arr2=np.array([[[1, 2, 3], [3, 4, 5]]])
print(arr2.ndim)

3


In [ ]:
#Integer array indexing
temp=arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print("\nElements at indices (0, 3), (1, 2), (2, 1),""(3, 0):\n", temp)


Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]


In [ ]:
import numpy as np
arr = np.array([[-1, 2, 0, 4], [4, -0.5, 6, 0], [2.6, 0, 7, 8], [3, -7, 4, 2.0]])

In [ ]:
#Boolean array indexing
cond = arr>2

#cond is a boolean array
temp = arr[cond]
print("Elements greater than 2:\n", temp)

Elements greater than 2:
 [4.  4.  6.  2.6 7.  8.  3.  4. ]


In [ ]:
#Joining two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print("Original arrays:\n", arr1, arr2) 
print("\nJoined array:\n", arr)

Original arrays:
 [1 2 3] [4 5 6]

Joined array:
 [1 2 3 4 5 6]


In [ ]:
#Horizontal Join
arr = np.hstack((arr1, arr2))
print("Horizontal joining:\n", arr)

Horizontal joining:
 [1 2 3 4 5 6]


In [ ]:
#Vertical join
arr = np.vstack((arr1, arr2))
print("Vertical joining:\n", arr)

Vertical joining:
 [[1 2 3]
 [4 5 6]]


In [ ]:
#Depth join
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
#Splitting of array
arr = np.array ([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print("Original array:\n", arr)
print("\nSplitted array in another form:")

#Displaying splitted array in another form
print(newarr[0])
print(newarr[1])
print(newarr[2])

Original array:
 [1 2 3 4 5 6]

Splitted array in another form:
[1 2]
[3 4]
[5 6]
